---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "grafana.fullname" . }}
  labels:
    {{- include "grafana.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.grafana.storage.size }}
  {{- if .Values.grafana.storage.storageClass }}
  storageClassName: {{ .Values.grafana.storage.storageClass }}
  {{- end }}