{{- if .Values.keyVault.enabled }}
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ include "grafana.fullname" . }}-kv-secrets
  labels:
    {{- include "grafana.labels" . | nindent 4 }}
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    clientID: {{ .Values.keyVault.userAssignedClientID | quote }}
    keyvaultName: {{ .Values.keyVault.name | quote }}
    cloudName: ""
    objects: |
      array:
        - |
          objectName: {{ .Values.keyVault.secrets.adminPassword }}
          objectType: secret
          objectVersion: ""
    tenantId: {{ .Values.keyVault.tenantId | quote }}
  secretObjects:
  - secretName: {{ include "grafana.fullname" . }}-admin-secret
    type: Opaque
    data:
    - objectName: {{ .Values.keyVault.secrets.adminPassword }}
      key: admin-password
{{- end }}
