{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "grafana.serviceAccountName" . }}
  labels:
    {{- include "grafana.labels" . | indent 4 }}
  annotations:
    {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | indent 4 }}
    {{- end }}
    {{- if .Values.keyVault.enabled }}
    azure.workload.identity/client-id: {{ .Values.keyVault.userAssignedClientID | quote }}
    {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
{{- end }}
