---
prometheus:
  image:
    repository: prom/prometheus
    tag: v3.4.0
    pullPolicy: IfNotPresent

  service:
    type: ClusterIP
    port: 9090
    targetPort: 9090

  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi

  securityContext:
    runAsUser: 65534
    runAsGroup: 65534
    fsGroup: 65534
  storage:
    size: 10Gi
    storageClass: "default"

  retention: "15d"

  config:
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']

      - job_name: 'node-exporter'
        static_configs:
          - targets: ['node-exporter-prometheus-node-exporter.node-exporter.svc.cluster.local:9100']

      - job_name: 'kube-state-metrics'
        static_configs:
          - targets: ['kube-state-metrics.kube-state-metrics.svc.cluster.local:8080']
      # cAdvisor - container resource metrics
      - job_name: 'cadvisor'
        kubernetes_sd_configs:
          - role: node
        scheme: https
        tls_config:
          ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
          insecure_skip_verify: true
        bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
        relabel_configs:
          - action: labelmap
            regex: __meta_kubernetes_node_label_(.+)
          - target_label: __address__
            replacement: kubernetes.default.svc:443
          - source_labels: [__meta_kubernetes_node_name]
            regex: (.+)
            target_label: __metrics_path__
            replacement: /api/v1/nodes/$1/proxy/metrics/cadvisor
      - job_name: 'kubelet'
        kubernetes_sd_configs:
          - role: node
        scheme: https
        tls_config:
          ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
          insecure_skip_verify: true
        bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
        relabel_configs:
          - action: labelmap
            regex: __meta_kubernetes_node_label_(.+)
          - target_label: __address__
            replacement: kubernetes.default.svc:443
          - source_labels: [__meta_kubernetes_node_name]
            regex: (.+)
            target_label: __metrics_path__
            replacement: /api/v1/nodes/$1/proxy/metrics
      - job_name: 'cert-manager'
        kubernetes_sd_configs:
        - role: endpoints
          namespaces:
            names:
            - cert-manager
        relabel_configs:
        - source_labels: [__meta_kubernetes_service_name]
          action: keep
          regex: cert-manager
        - source_labels: [__meta_kubernetes_endpoint_port_name]
          action: keep
          regex: tcp-prometheus-servicemonitor
        - source_labels: [__meta_kubernetes_namespace]
          target_label: namespace
        - source_labels: [__meta_kubernetes_pod_name]
          target_label: pod
        - source_labels: [__meta_kubernetes_service_name]
          target_label: service
      
      # Helm Exporter - for Helm release metrics
      - job_name: 'helm-exporter'
        static_configs:
          - targets: ['helm-exporter.monitoring.svc.cluster.local:8080']
        scrape_interval: 60s
        metrics_path: '/metrics'

serviceAccount:
  create: true
  name: ""
  annotations: {}
  automount: true
fullnameOverride: "prometheus"
ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: prometheus.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

nodeSelector: {}
tolerations: []
affinity: {}