---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "prometheus.fullname" . }}-config
  labels:
    {{- include "prometheus.labels" . | nindent 4 }}
data:
  prometheus.yml: |
    global:
      {{- toYaml .Values.prometheus.config.global | nindent 6 }}

    scrape_configs:
      {{- toYaml .Values.prometheus.config.scrape_configs | nindent 6 }}