apiVersion: v2
name: grafana
description: A simple Grafana Helm chart for container monitoring
type: application
version: 3.0.0
appVersion: "10.2.0"
keywords:
  - grafana
  - monitoring
  - visualization
home: https://grafana.com/
sources:
  - https://github.com/grafana/grafana
maintainers:
  - name: elmi abdullahi
    email: elmi.abdullahi91@gmail.com
