apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: test-certificate
  namespace: default
spec:
  secretName: test-cert-tls
  commonName: test.${AZURE_DNS_ZONE}
  dnsNames:
    - test.${AZURE_DNS_ZONE}
  issuerRef:
    name: letsencrypt-staging  # Use staging first to avoid hitting rate limits
    kind: ClusterIssuer
  duration: 2160h # 90 days
  renewBefore: 360h # 15 days
