name: Build and Push Helm Exporter

on:
  push:
    branches: [ main, develop ]
    paths: 
      - 'helm-exporter/**'
  pull_request:
    branches: [ main ]
    paths: 
      - 'helm-exporter/**'
  workflow_dispatch:
    inputs:
      tag:
        description: 'Custom tag for the image'
        required: false
        default: ''

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: elmi70/helm-exporter

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=sha,prefix={{branch}}-
          type=raw,value=latest,enable={{is_default_branch}}
          type=raw,value=${{ github.event.inputs.tag }},enable=${{ github.event.inputs.tag != '' }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./helm-exporter
        file: ./helm-exporter/Dockerfile
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        platforms: linux/amd64,linux/arm64
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Output image details
      run: |
        echo "Image pushed to:"
        echo "${{ steps.meta.outputs.tags }}" | while read tag; do
          echo "  - $tag"
        done
        echo ""
        echo "To use this image in Kubernetes:"
        echo "image: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest"
